version: "3.7"
services:
  ecom:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000/ecom/healthcheck | grep OK"]
      interval: 10s
      timeout: 2s
      retries: 5
    restart: always